[2023-12-17T11:18:33.416+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-11-22T04:00:00+00:00/task_id=Create_Table permission to 509
[2023-12-17T11:18:33.429+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-11-22T04:00:00+00:00/task_id=Create_Table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-11-22T04:00:00+00:00/task_id=Create_Table'
[2023-12-17T11:18:33.674+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-11-22T04:00:00+00:00/task_id=Create_Table permission to 509
[2023-12-17T11:18:33.675+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-11-22T04:00:00+00:00/task_id=Create_Table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-11-22T04:00:00+00:00/task_id=Create_Table'
[2023-12-17T11:18:33.930+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality.Create_Table scheduled__2023-11-22T04:00:00+00:00 [queued]>
[2023-12-17T11:18:33.995+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality.Create_Table scheduled__2023-11-22T04:00:00+00:00 [queued]>
[2023-12-17T11:18:33.999+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-17T11:18:34.606+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Create_Table> on 2023-11-22 04:00:00+00:00
[2023-12-17T11:18:34.645+0000] {standard_task_runner.py:57} INFO - Started process 2060 to run task
[2023-12-17T11:18:34.655+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'air_quality', 'Create_Table', 'scheduled__2023-11-22T04:00:00+00:00', '--job-id', '326', '--raw', '--subdir', 'DAGS_FOLDER/airQuality.py', '--cfg-path', '/tmp/tmpsrq9txkf']
[2023-12-17T11:18:34.680+0000] {standard_task_runner.py:85} INFO - Job 326: Subtask Create_Table
[2023-12-17T11:18:34.955+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-11-22T04:00:00+00:00/task_id=Create_Table permission to 509
[2023-12-17T11:18:34.957+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-11-22T04:00:00+00:00/task_id=Create_Table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-11-22T04:00:00+00:00/task_id=Create_Table'
[2023-12-17T11:18:34.961+0000] {task_command.py:416} INFO - Running <TaskInstance: air_quality.Create_Table scheduled__2023-11-22T04:00:00+00:00 [running]> on host 1a58977f5573
[2023-12-17T11:18:35.234+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ghifari' AIRFLOW_CTX_DAG_ID='air_quality' AIRFLOW_CTX_TASK_ID='Create_Table' AIRFLOW_CTX_EXECUTION_DATE='2023-11-22T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-22T04:00:00+00:00'
[2023-12-17T11:18:35.316+0000] {base.py:73} INFO - Using connection ID 'neonServerDB-Postgres' for task execution.
[2023-12-17T11:18:35.873+0000] {airQuality.py:160} INFO - Table air_quality Already Exist
[2023-12-17T11:18:35.905+0000] {python.py:194} INFO - Done. Returned value was: 
        CREATE TABLE air_quality (
            id serial primary key, 
            city varchar(250),
            country varchar(250), 
            unit varchar(20), 
            last_value float8, 
            lat float8,
            lng float8
        )
    
[2023-12-17T11:18:35.943+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=air_quality, task_id=Create_Table, execution_date=20231122T040000, start_date=20231217T111833, end_date=20231217T111835
[2023-12-17T11:18:35.997+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-17T11:18:36.067+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-12-28T16:54:11.118+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-11-22T04:00:00+00:00/task_id=Create_Table permission to 509
[2023-12-28T16:54:11.124+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-11-22T04:00:00+00:00/task_id=Create_Table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-11-22T04:00:00+00:00/task_id=Create_Table'
[2023-12-28T16:54:11.272+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-11-22T04:00:00+00:00/task_id=Create_Table permission to 509
[2023-12-28T16:54:11.280+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-11-22T04:00:00+00:00/task_id=Create_Table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-11-22T04:00:00+00:00/task_id=Create_Table'
[2023-12-28T16:54:11.519+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality.Create_Table scheduled__2023-11-22T04:00:00+00:00 [queued]>
[2023-12-28T16:54:11.652+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality.Create_Table scheduled__2023-11-22T04:00:00+00:00 [queued]>
[2023-12-28T16:54:11.653+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-28T16:54:11.782+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Create_Table> on 2023-11-22 04:00:00+00:00
[2023-12-28T16:54:11.815+0000] {standard_task_runner.py:57} INFO - Started process 854 to run task
[2023-12-28T16:54:11.835+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'air_quality', 'Create_Table', 'scheduled__2023-11-22T04:00:00+00:00', '--job-id', '1037', '--raw', '--subdir', 'DAGS_FOLDER/airQuality.py', '--cfg-path', '/tmp/tmp34xekcue']
[2023-12-28T16:54:11.843+0000] {standard_task_runner.py:85} INFO - Job 1037: Subtask Create_Table
[2023-12-28T16:54:12.264+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-11-22T04:00:00+00:00/task_id=Create_Table permission to 509
[2023-12-28T16:54:12.267+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-11-22T04:00:00+00:00/task_id=Create_Table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-11-22T04:00:00+00:00/task_id=Create_Table'
[2023-12-28T16:54:12.282+0000] {task_command.py:416} INFO - Running <TaskInstance: air_quality.Create_Table scheduled__2023-11-22T04:00:00+00:00 [running]> on host d67dd4682ccf
[2023-12-28T16:54:12.760+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ghifari' AIRFLOW_CTX_DAG_ID='air_quality' AIRFLOW_CTX_TASK_ID='Create_Table' AIRFLOW_CTX_EXECUTION_DATE='2023-11-22T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-22T04:00:00+00:00'
[2023-12-28T16:54:12.801+0000] {base.py:73} INFO - Using connection ID 'neonServerDB-Postgres' for task execution.
[2023-12-28T16:54:17.104+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airQuality.py", line 133, in createTableSQL
    cursor.execute(createQuery)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(air_quality_id_seq, 2200) already exists.

[2023-12-28T16:54:17.210+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=air_quality, task_id=Create_Table, execution_date=20231122T040000, start_date=20231228T165411, end_date=20231228T165417
[2023-12-28T16:54:17.419+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1037 for task Create_Table (duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(air_quality_id_seq, 2200) already exists.
; 854)
[2023-12-28T16:54:17.514+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-28T16:54:17.663+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
