[2023-12-15T15:19:49.874+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T15:19:46.965092+00:00/task_id=Transformation permission to 509
[2023-12-15T15:19:49.875+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T15:19:46.965092+00:00/task_id=Transformation permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T15:19:46.965092+00:00/task_id=Transformation'
[2023-12-15T15:19:49.903+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T15:19:46.965092+00:00/task_id=Transformation permission to 509
[2023-12-15T15:19:49.903+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T15:19:46.965092+00:00/task_id=Transformation permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T15:19:46.965092+00:00/task_id=Transformation'
[2023-12-15T15:19:49.935+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality.Transformation manual__2023-12-15T15:19:46.965092+00:00 [queued]>
[2023-12-15T15:19:49.945+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality.Transformation manual__2023-12-15T15:19:46.965092+00:00 [queued]>
[2023-12-15T15:19:49.945+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-15T15:19:49.962+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Transformation> on 2023-12-15 15:19:46.965092+00:00
[2023-12-15T15:19:49.965+0000] {standard_task_runner.py:57} INFO - Started process 3327 to run task
[2023-12-15T15:19:49.968+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'air_quality', 'Transformation', 'manual__2023-12-15T15:19:46.965092+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/airQuality.py', '--cfg-path', '/tmp/tmp48w5180_']
[2023-12-15T15:19:49.969+0000] {standard_task_runner.py:85} INFO - Job 58: Subtask Transformation
[2023-12-15T15:19:50.009+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T15:19:46.965092+00:00/task_id=Transformation permission to 509
[2023-12-15T15:19:50.010+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T15:19:46.965092+00:00/task_id=Transformation permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T15:19:46.965092+00:00/task_id=Transformation'
[2023-12-15T15:19:50.012+0000] {task_command.py:416} INFO - Running <TaskInstance: air_quality.Transformation manual__2023-12-15T15:19:46.965092+00:00 [running]> on host d739bc9bef06
[2023-12-15T15:19:50.086+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ghifari' AIRFLOW_CTX_DAG_ID='air_quality' AIRFLOW_CTX_TASK_ID='Transformation' AIRFLOW_CTX_EXECUTION_DATE='2023-12-15T15:19:46.965092+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-15T15:19:46.965092+00:00'
[2023-12-15T15:19:50.087+0000] {python.py:194} INFO - Done. Returned value was: <coroutine object transformation at 0x7ffad408d840>
[2023-12-15T15:19:50.094+0000] {xcom.py:661} ERROR - Object of type coroutine is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-12-15T15:19:50.096+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 178, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'coroutine'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2479, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 244, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 659, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type coroutine is not JSON serializable
[2023-12-15T15:19:50.105+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=air_quality, task_id=Transformation, execution_date=20231215T151946, start_date=20231215T151949, end_date=20231215T151950
[2023-12-15T15:19:50.119+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 58 for task Transformation (Object of type coroutine is not JSON serializable; 3327)
[2023-12-15T15:19:50.141+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-15T15:19:50.158+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
