[2023-12-17T05:02:34.645+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-17T05:02:26.563739+00:00/task_id=Check_Table permission to 509
[2023-12-17T05:02:34.647+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-17T05:02:26.563739+00:00/task_id=Check_Table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-17T05:02:26.563739+00:00/task_id=Check_Table'
[2023-12-17T05:02:34.678+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-17T05:02:26.563739+00:00/task_id=Check_Table permission to 509
[2023-12-17T05:02:34.679+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-17T05:02:26.563739+00:00/task_id=Check_Table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-17T05:02:26.563739+00:00/task_id=Check_Table'
[2023-12-17T05:02:34.713+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality.Check_Table manual__2023-12-17T05:02:26.563739+00:00 [queued]>
[2023-12-17T05:02:34.725+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality.Check_Table manual__2023-12-17T05:02:26.563739+00:00 [queued]>
[2023-12-17T05:02:34.726+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-17T05:02:34.742+0000] {taskinstance.py:1382} INFO - Executing <Task(BranchPythonOperator): Check_Table> on 2023-12-17 05:02:26.563739+00:00
[2023-12-17T05:02:34.746+0000] {standard_task_runner.py:57} INFO - Started process 832 to run task
[2023-12-17T05:02:34.750+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'air_quality', 'Check_Table', 'manual__2023-12-17T05:02:26.563739+00:00', '--job-id', '223', '--raw', '--subdir', 'DAGS_FOLDER/airQuality.py', '--cfg-path', '/tmp/tmp5_87pa76']
[2023-12-17T05:02:34.751+0000] {standard_task_runner.py:85} INFO - Job 223: Subtask Check_Table
[2023-12-17T05:02:34.842+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-17T05:02:26.563739+00:00/task_id=Check_Table permission to 509
[2023-12-17T05:02:34.843+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-17T05:02:26.563739+00:00/task_id=Check_Table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-17T05:02:26.563739+00:00/task_id=Check_Table'
[2023-12-17T05:02:34.848+0000] {task_command.py:416} INFO - Running <TaskInstance: air_quality.Check_Table manual__2023-12-17T05:02:26.563739+00:00 [running]> on host 1a58977f5573
[2023-12-17T05:02:34.988+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ghifari' AIRFLOW_CTX_DAG_ID='air_quality' AIRFLOW_CTX_TASK_ID='Check_Table' AIRFLOW_CTX_EXECUTION_DATE='2023-12-17T05:02:26.563739+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-17T05:02:26.563739+00:00'
[2023-12-17T05:02:35.008+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 226, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airQuality.py", line 190, in checkTable
    if resultCreateTable.psycopg.errors.DuplicateTable:
AttributeError: 'NoneType' object has no attribute 'psycopg'
[2023-12-17T05:02:35.033+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=air_quality, task_id=Check_Table, execution_date=20231217T050226, start_date=20231217T050234, end_date=20231217T050235
[2023-12-17T05:02:35.063+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 223 for task Check_Table ('NoneType' object has no attribute 'psycopg'; 832)
[2023-12-17T05:02:35.096+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-17T05:02:35.130+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
